"use strict"
define("people/app",["exports","people/resolver","ember-load-initializers","people/config/environment","people/single-spa-ember"],function(e,n,t,o,r){Object.defineProperty(e,"__esModule",{value:!0}),e.unmount=e.mount=e.bootstrap=void 0
var i=Ember.Application.extend({modulePrefix:o.default.modulePrefix,podModulePrefix:o.default.podModulePrefix,Resolver:n.default});(0,t.default)(i,o.default.modulePrefix),loader.noConflict({require:"peopleRequire",requirejs:"peopleRequireJS"}),e.default=i
var a=(0,r.default)({App:i,appName:"people",createOpts:{rootElement:"#people"}}),l=a.bootstrap,p=a.mount,s=a.unmount
e.bootstrap=l,e.mount=p,e.unmount=s}),define("people/helpers/app-version",["exports","people/config/environment","ember-cli-app-version/utils/regexp"],function(e,n,t){function o(e){var o=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{},r=n.default.APP.version,i=o.versionOnly||o.hideSha,a=o.shaOnly||o.hideVersion,l=null
return i&&(o.showExtended&&(l=r.match(t.versionExtendedRegExp)),l||(l=r.match(t.versionRegExp))),a&&(l=r.match(t.shaRegExp)),l?l[0]:r}Object.defineProperty(e,"__esModule",{value:!0}),e.appVersion=o,e.default=Ember.Helper.helper(o)}),define("people/helpers/pluralize",["exports","ember-inflector/lib/helpers/pluralize"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0}),e.default=n.default}),define("people/helpers/singularize",["exports","ember-inflector/lib/helpers/singularize"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0}),e.default=n.default}),define("people/initializers/app-version",["exports","ember-cli-app-version/initializer-factory","people/config/environment"],function(e,n,t){Object.defineProperty(e,"__esModule",{value:!0})
var o=void 0,r=void 0
t.default.APP&&(o=t.default.APP.name,r=t.default.APP.version),e.default={name:"App Version",initialize:(0,n.default)(o,r)}}),define("people/initializers/container-debug-adapter",["exports","ember-resolver/resolvers/classic/container-debug-adapter"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0}),e.default={name:"container-debug-adapter",initialize:function(){var e=arguments[1]||arguments[0]
e.register("container-debug-adapter:main",n.default),e.inject("container-debug-adapter:main","namespace","application:main")}}}),define("people/initializers/ember-data",["exports","ember-data/setup-container","ember-data"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0}),e.default={name:"ember-data",initialize:n.default}}),define("people/initializers/export-application-global",["exports","people/config/environment"],function(e,n){function t(){var e=arguments[1]||arguments[0]
if(!1!==n.default.exportApplicationGlobal){var t
if("undefined"!=typeof window)t=window
else if("undefined"!=typeof global)t=global
else{if("undefined"==typeof self)return
t=self}var o,r=n.default.exportApplicationGlobal
o="string"==typeof r?r:Ember.String.classify(n.default.modulePrefix),t[o]||(t[o]=e,e.reopen({willDestroy:function(){this._super.apply(this,arguments),delete t[o]}}))}}Object.defineProperty(e,"__esModule",{value:!0}),e.initialize=t,e.default={name:"export-application-global",initialize:t}}),define("people/instance-initializers/ember-data",["exports","ember-data/initialize-store-service"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0}),e.default={name:"ember-data",initialize:n.default}}),define("people/resolver",["exports","ember-resolver"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0}),e.default=n.default}),define("people/router",["exports","people/config/environment"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0})
var t=Ember.Router.extend({location:n.default.locationType,rootURL:n.default.rootURL})
t.map(function(){}),e.default=t}),define("people/services/ajax",["exports","ember-ajax/services/ajax"],function(e,n){Object.defineProperty(e,"__esModule",{value:!0}),Object.defineProperty(e,"default",{enumerable:!0,get:function(){return n.default}})}),define("people/single-spa-ember",["exports"],function(e){Object.defineProperty(e,"__esModule",{value:!0}),e.default=function(e){if("object"!==(void 0===e?"undefined":n(e)))throw new Error("single-spa-ember requires a configuration object")
var a=Object.assign(t,e)
if(!a.App)throw new Error("single-spa-ember must be passed opts.App")
if(a.createOpts&&"object"!==n(a.createOpts))throw new Error("single-spa-ember: createOpts must be an object to be passed to App.create()")
return{bootstrap:o.bind(null,a),mount:r.bind(null,a),unmount:i.bind(null,a)}},e.loadEmberApp=function(e,n){var t=arguments.length>2&&void 0!==arguments[2]?arguments[2]:null
return new Promise(function(o,r){if("string"==typeof e)if("string"==typeof n)if(t&&"string"!=typeof t)r(new Error("single-spa-ember vendorUrl (the third argument) is optional, but must be a string if present"))
else if(t){var i=document.createElement("script")
i.src=t,i.async=!0,i.onload=a,i.onerror=r,document.head.appendChild(i)}else a()
else r(new Error("single-spa-ember requires an appUrl string as the second argument"))
else r(new Error("single-spa-ember requires an appName string as the first argument"))
function a(){var t=document.createElement("script")
t.src=n,t.async=!0,t.onload=function(){o(window.require(e+"/app"))},t.onerror=r,document.head.appendChild(t)}})}
var n="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},t={App:null,createOpts:{}}
function o(){return Promise.resolve()}function r(e){return Promise.resolve().then(function(){if(window.__people=window.__people||{},window.__people.Ember){var n=window.__people.Ember
window.Ember=n}if(window.__sspaEmber.people){var t=window.__sspaEmber.people,o=t.appUrl
t.vendorUrl;(function(e,n){var t=document.createElement("script")
t.src=n,t.async=!0,t.onload=function(){window.require(e+"/app")},document.head.appendChild(t)})("people",o)}e.applicationInstance=e.App.create(e.createOpts)})}function i(e){return Promise.resolve().then(function(){e.applicationInstance.destroy(),e.applicationInstance=null,window.__people={Ember:window.Ember},delete window.Ember,document.querySelectorAll("script").forEach(function(e){var n=window.__sspaEmber.people,t=n.appUrl,o=n.vendorUrl
e.src!==t&&e.src!==o||document.head.removeChild(e)})})}}),define("people/templates/application",["exports"],function(e){Object.defineProperty(e,"__esModule",{value:!0}),e.default=Ember.HTMLBars.template({id:"E9m0bbTJ",block:'{"symbols":[],"statements":[[7,"h1"],[11,"class","text-5xl text-center"],[9],[0,"People page"],[10],[0,"\\n"],[7,"h2"],[9],[0,"Ember version: 3.4.0"],[10],[0,"\\n"],[1,[21,"outlet"],false],[0,"\\n"]],"hasEval":false}',meta:{moduleName:"people/templates/application.hbs"}})}),define("people/config/environment",[],function(){var e={default:{modulePrefix:"people",environment:"production",rootURL:"/people/",locationType:"none",EmberENV:{FEATURES:{},EXTEND_PROTOTYPES:{Date:!1,String:!1}},APP:{name:"people",version:"0.0.0+cb11392a"},exportApplicationGlobal:!1}}
return Object.defineProperty(e,"__esModule",{value:!0}),e})
